### ISSUE TITLE
Plugin takes almost 14 seconds for startup activation

### ISSUE THREAD

**Issue by polarapfel** [Microsoft/vscode-azure-iot-toolkit#179] opened 2018-10-10 18:04 UTC
- Extension Name: azure-iot-toolkit
- Extension Version: 1.4.0
- OS Version: Windows_NT x64 10.0.17134
- VSCode version: 1.28.0

Plugin takes almost 14 seconds for startup activation

**Comment by formulahendry** [comment] 2018-10-11 01:09
Hi @polarapfel , since `Azure IoT Toolkit` depends on the `Azure Account` extension, could you please also share the startup time of `Azure Account`? That would help us narrow down which extension takes most of time to start up.

**Comment by polarapfel** [comment] 2018-10-11 20:55
@formulahendry 

Hi there,

Azure Account takes 25 seconds and IoT Toolkit shows 10 seconds apart from that in the "Running Extensions" tab in Code.

thanks,

Tobias

**Comment by formulahendry** [comment] 2018-10-12 04:44
Hi @polarapfel , is this issue always reproduced? And could you share the startup time data of other extensions? The startup time may also be affected by other extensions and your machine performance.

**Comment by polarapfel** [comment] 2018-10-12 17:01
@formulahendry, it's always reproduced. Azure IoT Toolkit and Azure Account each take at least 10 seconds to start while all other extensions start in less than 100ms.

**Comment by formulahendry** [comment] 2018-10-15 03:52
Related to https://github.com/Microsoft/vscode/issues/60318 

> The notification was a great way to become aware that some extensions keep the extension host busy. However, as is, the notification is not helpful for the general user and it motivates the creation of unhelpful issues. We need to remove the notification until we have a better flow.

After you upgrade to VS Code 1.28.1, the notification will no longer show.
I will still keep this open in case any user has similar experience, or this issue has any side effect on the user experience.

**Comment by formulahendry** [comment] 2019-01-07 09:16
Hi @polarapfel , in 2.1.0, we have use Webpack to improve the performance, so closing this issue. Feel free to reopen or create a new issue if you still meet with similar issue.

**Closed by formulahendry** 2019-01-07 09:16 UTC
Labels: fyi
