### ISSUE TITLE
send button not work when select the devices input box doesn't lose its focus

### ISSUE THREAD

**Issue by czgtest** [microsoft/vscode-azure-iot-toolkit#406] opened 2019-10-10 01:31 UTC
Repro on : v2.11.0-rc
step:
1. open D2C message WebView 
2. select the devices you want to send messages 
here  the input box doesn't lose its focus, you focus on other fields,
you don't click the blank area in the WebView, 

3 click the send button.
here the send button not work when click it in the first time.

**Comment by blackchoey** [comment] 2019-10-11 03:20
When the current focus is on the drop down list, clicking other places will first reset the focus. I checked the behavior of github and azure devops, they have same behavior. Close this as by design.

**Closed** 2019-10-11 07:15 UTC
