### ISSUE TITLE
Starting D2C monitoring after stopping it fails

### ISSUE THREAD

**Issue by wickste** [Microsoft/vscode-azure-iot-toolkit#290] opened 2019-04-02 22:48 UTC
When I stop D2C monitoring, then restarting it fails with the below:

`[IoTHubMonitor] Unauthorized access. 'Listen' claim(s) are required to perform this operation. Resource: 'sb://iothub-ns-iotedgedem-1449658-4cf18c9347.servicebus.windows.net/iotedgedemohub-mza662os7k/consumergroups/$default/partitions/0'. TrackingId:5de2294a1f24434bbb07af7f468cf318_G8, SystemTracker:gateway5, Timestamp:2019-04-02T19:23:11
`

**Comment by formulahendry** [comment] 2019-04-03 06:17
Hi @wickste , could you please try using https://github.com/Azure/azure-iot-sdk-csharp/tree/master/tools/DeviceExplorer to see whether there is the same error? It could help us to figure out whether the issue is from client side or service side. Thanks a lot.

**Comment by formulahendry** [comment] 2019-04-09 06:49
With deep investigation, I find there is possibility related the `@azure/event-hubs` npm package which is used by Azure IoT Hub Toolkit to monitor the D2C message. https://github.com/Azure/azure-sdk-for-js/issues/2057 is created to track.

**Comment by formulahendry** [comment] 2019-04-25 05:36
The @azure/event-hubs SDK has fixed this issue. We have tested it (running it for several hours) and published a new release v2.6.0 of Azure IoT Hub Toolkit to include the latest version of @azure/event-hubs SDK.
https://marketplace.visualstudio.com/items?itemName=vsciot-vscode.azure-iot-toolkit 
The issue is expected to be fixed in new release. Please kindly let us know if you still meet with similar issue in the future, I will help redirect the issue to the SDK team. Thanks!

**Closed by formulahendry** 2019-04-25 05:36 UTC
Labels: need more info
