### ISSUE TITLE
What does the color mean?

### ISSUE THREAD

**Issue by lordbah** [microsoft/vscode-azure-iot-toolkit#214] opened 2018-11-26 18:54 UTC
Under AZURE IOT HUB DEVICES in vscode some devices have a blue chip and some have a green chip. I thought it might mean green was online and blue was offline, but today I can see messages coming from a blue chip, so that's not the answer. What do the colors mean?

**Comment by adashen** [comment] 2018-11-27 03:39
It shows the connection state of the module. Toolkit got these information from IoT Hub. Green means the module connection state is "connected", blue otherwise.

**Comment by lordbah** [comment] 2018-11-27 04:21
So it's what I thought initially. There must be a bug where the icon color isn't kept up-to-date.

**Comment by adashen** [comment] 2018-11-29 09:13
The issue is caused by iot hub which doesn't update the module status correctly. So add external dependency.

**Comment by formulahendry** [comment] 2018-12-10 05:13
Hi @lordbah , the connection state is updated only for devices using MQTT or AMQP, please make sure you are using MQTT or AMQP, not HTTP. Also, it is based on protocol-level pings (MQTT pings, or AMQP pings), and it can have a maximum delay of only 5 minutes. For these reasons, there can be false positives. You refer to https://docs.microsoft.com/en-us/azure/iot-hub/iot-hub-devguide-identity-registry#device-heartbeat for more details.

**Comment by formulahendry** [comment] 2019-12-24 06:34
Have a wiki page taking about the meaning of the module status: https://github.com/microsoft/vscode-azure-iot-toolkit/wiki/FAQ#how-to-understand-the-connection-state-and-running-status-of-modules

So closing this issue. Feel free to re-open or create a new issue if you need other help.

**Closed by formulahendry** 2019-12-24 06:34 UTC
Labels: external
