### ISSUE TITLE
When monitoring D2C messages for a period of tim (>1h) it suddenly stops working

### ISSUE THREAD

**Issue by wickste** [Microsoft/vscode-azure-iot-toolkit#291] opened 2019-04-02 22:50 UTC
New messages are no longer shown. No error message is displayed, it just stops working.

**Comment by formulahendry** [comment] 2019-04-03 06:18
Hi @wickste , could you please try using https://github.com/Azure/azure-iot-sdk-csharp/tree/master/tools/DeviceExplorer to see whether there is similar behavior? It could help us to figure out whether the issue is from client side or service side. Thanks a lot.

**Comment by formulahendry** [comment] 2019-04-09 06:49
With deep investigation, I find there is possibility related the `@azure/event-hubs` npm package which is used by Azure IoT Hub Toolkit to monitor the D2C message. https://github.com/Azure/azure-sdk-for-js/issues/2057 is created to track.

**Comment by formulahendry** [comment] 2019-04-25 05:35
The @azure/event-hubs SDK has fixed this issue. We have tested it (running it for several hours) and published a new release v2.6.0 of Azure IoT Hub Toolkit to include the latest version of @azure/event-hubs SDK.
https://marketplace.visualstudio.com/items?itemName=vsciot-vscode.azure-iot-toolkit 
The issue is expected to be fixed in new release. Please kindly let us know if you still meet with similar issue in the future, I will help redirect the issue to the SDK team. Thanks!

**Closed by formulahendry** 2019-04-25 05:35 UTC
Labels: need more info
